openapi: 3.0.3
info:
  title: Service Private API
  description: This is a sample API description.
  version: 0.0.1

paths:
  /status:
    get:
      summary: Get service status
      description: Retrieve the current status of the service.
      operationId: getServiceStatus
      tags:
        - Status
      responses:
        '200':
          description: Service status
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "ok"
        '500':
          description: Internal server error
  /restart:
    post:
      summary: Restart service
      description: Restart the service.
      operationId: restartService
      tags:
        - Service
      responses:
        '200':
          description: Service restarted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Service restarted"
        '503':
          description: Service unavailable
  /shoutdown:
    post:
      summary: Shutdown service
      description: Shutdown the service.
      operationId: shutdownService
      tags:
        - Service
      responses:
        '200':
          description: Service shutdown successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Service shutdown"
        '503':
          description: Service unavailable
  /tasks/transfer/{taskUUID}:
    post:
      summary: Transfer task
      description: Transfer a task to another service instance.
      operationId: transferTask
      tags:
        - Tasks
      parameters:
        - name: taskId
          in: path
          description: ID of the task to transfer
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Task transferred successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Task transferred"
        '404':
          description: Task not found
        '500':
          description: Internal server error
  /tasks/stop/{taskUUID}:
    delete:
      summary: Stop task
      description: Stop a running task.
      operationId: stopTask
      tags:
        - Tasks
      parameters:
        - name: taskId
          in: path
          description: ID of the task to stop
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Task stopped successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Task stopped"
        '404':
          description: Task not found
        '500':
          description: Internal server error